os: linux
dist: focal
language: python
name: MSVC
python: "3.8.12"

jobs:
  fast_finish: true
  include:
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set changeps1 no
        - conda update -q conda -c conda-forge -y
#         - wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
#         - ./bin/micromamba shell init -s bash -p ~/micromamba
#         - source ~/.bashrc
#         - micromamba activate
#         - micromamba env create --file requirements.yml --yes
#         - micromamba activate msvc_env_mm
        - conda env create --file requirements.yml
        - conda activate msvc_env_mm
      install:
        # - micromamba install -y codecov pytest pytest-cov pytest-mpl -c conda-forge
        - conda install -y codecov pytest pytest-cov pytest-mpl -c conda-forge
      script:
        - python --version
        - python -m pytest --cov=msvc/src msvc/tests --mpl
      after_success:
        - codecov
        - deactivate
