os: linux
dist: focal
language: python
name: MSVC
python: "3.8.12"

jobs:
  fast_finish: true
  include:
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set changeps1 no
        - conda update -q conda -c conda-forge -y
        - wget -qO- https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        - eval "$(./bin/micromamba shell hook -s posix)"
        - source ~/.bashrc
        - micromamba env create --files requirements.yml --yes
        - micromamba activate msvc_env_mm
      install:
        - micromamba install codecov pytest pytest-cov pytest-mpl -c conda-forge -y
      script:
        - python --version
        - python -m pytest --cov=msvc/src msvc/tests --mpl
      after_success:
        - codecov
        - deactivate
